"use client"
//import './globals.css'

// import `ChakraProvider` component
import { ChakraProvider } from '@chakra-ui/react'

// import rainbowKit component
import '@rainbow-me/rainbowkit/styles.css';

import {
  getDefaultWallets,
  RainbowKitProvider,
} from '@rainbow-me/rainbowkit';
import { configureChains, createConfig, WagmiConfig } from 'wagmi';
import {
  hardhat
} from 'wagmi/chains';

import { publicProvider } from 'wagmi/providers/public';

import { goerli } from 'wagmi/chains'

const { chains, publicClient } = configureChains(
  [hardhat,goerli],
  [
    //alchemyProvider({ apiKey: process.env.ALCHEMY_ID }),
    publicProvider()
  ]
);

const { connectors } = getDefaultWallets({
  appName: 'My RainbowKit App',
  projectId: '75b6d44c78a26b310be5c3b37a399fb5',
  chains
});

const wagmiConfig = createConfig({
  autoConnect: false,
  connectors,
  publicClient
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title lang="en">Lumina</title>
      <body>
        <WagmiConfig config={wagmiConfig}>
            <RainbowKitProvider chains={chains}>
              <ChakraProvider>
                {children}
              </ChakraProvider>
            </RainbowKitProvider>
          </WagmiConfig>
      </body>
    </html>
  )
}
